# Spring DataSource Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/credicar-db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
spring.datasource.username=${CREDICAR_DB_USERNAME}
spring.datasource.password=${CREDICAR_DB_PASSWORD}


# Spring Data JPA Configuration
spring.jpa.show-sql=true